#undef TSTRUCT_INC_FILE
#define TSTRUCT_INC_FILE nvme-tstruct

#if !defined(NVME_TSTRUCT) || defined(TSTRUCT_HEADER_MULTI_READ)
#define NVME_TSTRUCT

#include "tstruct.h"

TSTRUCT(nvme_id_power_state,
	TSTRUCT_entries(
		__field(uint16_t, max_power)
		r_field(uint8_t, rsvd2)
		__field(uint8_t, flags)
		__field(uint32_t, entry_lat)
		__field(uint32_t, exit_lat)
		__field(uint8_t, read_tput)
		__field(uint8_t, read_lat)
		__field(uint8_t, write_tput)
		__field(uint8_t, write_lat)
		__field(uint16_t, idle_power)
		__field(uint8_t, idle_scale)
		r_field(uint8_t, rsvd19)
		__field(uint16_t, active_power)
		__field(uint8_t, active_work_scale)
		r_array(uint8_t, rsvd23, 9)
	)
)
TSTRUCT(nvme_id_ctrl,
	TSTRUCT_entries(
		__field(uint16_t, vid)
		__field(uint16_t, ssvid)
		__array(char, sn, 20)
		__array(char, mn, 40)
		__array(char, fr, 8)
		__field(uint8_t, rab)
		__array(uint8_t, ieee, 3)
		__field(uint8_t, cmic)
		__field(uint8_t, mdts)
		__field(uint16_t, cntlid)
		__field(uint32_t, ver)
		__field(uint32_t, rtd3r)
		__field(uint32_t, rtd3e)
		__field(uint32_t, oaes)
		__field(uint32_t, ctratt)
		r_array(uint8_t, rsvd100, 156)
		__field(uint16_t, oacs)
		__field(uint8_t, acl)
		__field(uint8_t, aerl)
		__field(uint8_t, frmw)
		__field(uint8_t, lpa)
		__field(uint8_t, elpe)
		__field(uint8_t, npss)
		__field(uint8_t, avscc)
		__field(uint8_t, apsta)
		__field(uint16_t, wctemp)
		__field(uint16_t, cctemp)
		__field(uint16_t, mtfa)
		__field(uint32_t, hmpre)
		__field(uint32_t, hmmin)
		__array(uint8_t, tnvmcap, 16)
		__array(uint8_t, unvmcap, 16)
		__field(uint32_t, rpmbs)
		r_array(uint8_t, rsvd316, 4)
		__field(uint16_t, kas)
		r_array(uint8_t, rsvd322, 190)
		__field(uint8_t, sqes)
		__field(uint8_t, cqes)
		__field(uint16_t, maxcmd)
		__field(uint32_t, nn)
		__field(uint16_t, oncs)
		__field(uint16_t, fuses)
		__field(uint8_t, fna)
		__field(uint8_t, vwc)
		__field(uint16_t, awun)
		__field(uint16_t, awupf)
		__field(uint8_t, nvscc)
		r_field(uint8_t, rsvd531)
		__field(uint16_t, acwu)
		r_array(uint8_t, rsvd534, 2)
		__field(uint32_t, sgls)
		r_array(uint8_t, rsvd540, 228)
		__array(char, subnqn, 256)
		r_array(uint8_t, rsvd1024, 768)
		__field(uint32_t, ioccsz)
		__field(uint32_t, iorcsz)
		__field(uint16_t, icdoff)
		__field(uint8_t, ctrattr)
		__field(uint8_t, msdbd)
		r_array(uint8_t, rsvd1804, 244)
		__array_struct(nvme_id_power_state, psd, 32, npss + 1)
		v_array(uint8_t, vs, 1024)
	)
)

TSTRUCT(nvme_lbaf,
	__field(uint16_t, ms)
	__field(uint8_t, ds)
	__field(uint8_t, rp)
)
TSTRUCT(nvme_id_ns,
	TSTRUCT_entries(
		l_field(uint64_t, nsze)
		l_field(uint64_t, ncap)
		l_field(uint64_t, nuse)
		__field(uint8_t, nsfeat)
		__field(uint8_t, nlbaf)
		__field(uint8_t, flbas)
		__field(uint8_t, mc)
		__field(uint8_t, dpc)
		__field(uint8_t, dps)
		__field(uint8_t, nmic)
		__field(uint8_t, rescap)
		__field(uint8_t, fpi)
		__field(uint8_t, rsvd33)
		__field(uint16_t, nawun)
		__field(uint16_t, nawupf)
		__field(uint16_t, nacwu)
		__field(uint16_t, nabsn)
		__field(uint16_t, nabo)
		__field(uint16_t, nabspf)
		r_field(uint16_t, rsvd46)
		__array(uint8_t, nvmcap, 16)
		__array(uint8_t, rsvd64, 40)
		__array(uint8_t, nguid, 16)
		__array(uint8_t, eui64, 8)
		__array_struct(nvme_lbaf, lbaf, 16, nlbaf + 1)
		r_array(uint8_t, rsvd192, 192)
		v_array(uint8_t, vs, 3712)
	)
)

TSTRUCT(nvme_smart_log,
	TSTRUCT_entries(
		__field(uint8_t, critical_warning)
		__array(uint8_t, temperature, 2)
		__field(uint8_t, avail_spare)
		__field(uint8_t, spare_thresh)
		__field(uint8_t, percent_used)
		r_array(uint8_t, rsvd6, 26)
		__array(uint8_t, data_units_read, 16)
		__array(uint8_t, data_units_written, 16)
		__array(uint8_t, host_reads, 16)
		__array(uint8_t, host_writes, 16)
		__array(uint8_t, ctrl_busy_time, 16)
		__array(uint8_t, power_cycles, 16)
		__array(uint8_t, power_on_hours, 16)
		__array(uint8_t, unsafe_shutdowns, 16)
		__array(uint8_t, media_errors, 16)
		__array(uint8_t, num_err_log_entries, 16)
		__field(uint32_t, warning_temp_time)
		__field(uint32_t, critical_comp_time)
		__array(uint16_t, temp_sensor, 8)
		r_array(uint8_t,rsvd216, 296)
	)
)

TSTRUCT(nvme_error_log,
	TSTRUCT_entries(
		l_field(uint64_t, error_count)
		__field(uint16_t, sqid)
		__field(uint16_t, cmdid)
		__field(uint16_t, status_field)
		__field(uint16_t, parm_error_location)
		l_field(uint64_t, lba)
		__field(uint32_t, nsid)
		__field(uint8_t, vs)
		r_array(uint8_t, resv, 35)
	)
)

TSTRUCT(nvme_firmware_log,
	TSTRUCT_entries(
		__field(uint8_t, afi)
		r_array(uint8_t, resv, 7)
		__array(uint64_t, frs, 7)
		r_array(uint8_t, resv2, 448)
	)
)

TSTRUCT(nvme_ns_list,
	TSTRUCT_entries(
		__array(uint32_t, ns_id, 1024)
	)
)

#endif
#include "define_tstruct.h"
